GET http://localhost:9090/?args=session&cmd=query&fcn=list

###
GET http://localhost:9090/?args=ssm&cmd=query&fcn=list


###
GET http://localhost:9090/?args=ProjectS2&cmd=query&fcn=ssm


###
GET http://localhost:9090/?args=session&cmd=query&fcn=list

###
GET http://localhost:9090/?args=9dc2ba38-9106-4309-9412-542255af5978&cmd=query&fcn=session

###
GET http://localhost:9090/?args=Project&cmd=query&fcn=ssm
